// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQc11fRDwT_WPOn2NrT4vwa1zxx36sjxo',
    appId: '1:771379252028:web:8fccf33b1236f816026c39',
    messagingSenderId: '771379252028',
    projectId: 'auth-riverpod-8d537',
    authDomain: 'auth-riverpod-8d537.firebaseapp.com',
    storageBucket: 'auth-riverpod-8d537.firebasestorage.app',
    measurementId: 'G-51YCQEPFZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6jq13UTUoi3BppkZm9JjcYRGKX5Ozj2A',
    appId: '1:771379252028:android:75264875dfba685f026c39',
    messagingSenderId: '771379252028',
    projectId: 'auth-riverpod-8d537',
    storageBucket: 'auth-riverpod-8d537.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0_zFpUx_z9TQlGALa52Gw1wXvJGFrJ38',
    appId: '1:771379252028:ios:60e98133e85ecf91026c39',
    messagingSenderId: '771379252028',
    projectId: 'auth-riverpod-8d537',
    storageBucket: 'auth-riverpod-8d537.firebasestorage.app',
    iosClientId: '771379252028-lo6079tjs6cacc4nkb9tf9kus8rhkmtv.apps.googleusercontent.com',
    iosBundleId: 'com.derodian.authRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0_zFpUx_z9TQlGALa52Gw1wXvJGFrJ38',
    appId: '1:771379252028:ios:60e98133e85ecf91026c39',
    messagingSenderId: '771379252028',
    projectId: 'auth-riverpod-8d537',
    storageBucket: 'auth-riverpod-8d537.firebasestorage.app',
    iosClientId: '771379252028-lo6079tjs6cacc4nkb9tf9kus8rhkmtv.apps.googleusercontent.com',
    iosBundleId: 'com.derodian.authRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQc11fRDwT_WPOn2NrT4vwa1zxx36sjxo',
    appId: '1:771379252028:web:e94f916ca5589d1e026c39',
    messagingSenderId: '771379252028',
    projectId: 'auth-riverpod-8d537',
    authDomain: 'auth-riverpod-8d537.firebaseapp.com',
    storageBucket: 'auth-riverpod-8d537.firebasestorage.app',
    measurementId: 'G-EBTWZ7B4T7',
  );
}
